# -*- coding: utf-8 -*-
"""Copy of COVID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B5D_TeZiYfM8gU6INjhzrckLHqTKuvZH

# **IMPORTING**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

df=pd.read_csv('covid_19_clean_complete.csv')
df.head(15)

df.shape

"""CONTAINS 49068 RECORDS WUTH 10 ATTRIBUTES"""

df.info()

df.isnull().sum()

df.describe()

total_confirmed = df.groupby("Country/Region")["Confirmed"].sum().sort_values(ascending=False).head(20).reset_index()

x_column = 'Confirmed'
y_column = 'Country/Region'

plt.figure(figsize=(10, 6))

sns.barplot(x=x_column, y=y_column, data=total_confirmed)

plt.xlabel('Total Confirmed Cases', fontsize=14)
plt.ylabel('Countries', fontsize=12)
plt.title('Top 20 Countries by Total Cases', fontsize=15)

plt.show()

"""# *USA Has the highest number of covid confirmed case....followed by BRAZIL which is more than 2 times of BRAZIL*"""

total_confirmed

"""**Descriptive statistics**"""

total_death = df.groupby("Country/Region")["Deaths"].sum().sort_values(ascending=False).head(20).reset_index()

x_column = 'Deaths'
y_column = 'Country/Region'

plt.figure(figsize=(10, 6))

sns.barplot(x=x_column, y=y_column, data=total_death)

plt.xlabel('Total death', fontsize=14)
plt.ylabel('Countries', fontsize=12)
plt.title('Top 20 Countries with Highest Total Deaths', fontsize=15)

plt.show()

"""# **Death due to covid**
# *Reported highest number in USA*
"""

total_death

total_recover = df.groupby("Country/Region")["Recovered"].sum().sort_values(ascending=False).head(20).reset_index()

x_column = 'Recovered'
y_column = 'Country/Region'

plt.figure(figsize=(10, 6))

sns.barplot(x=x_column, y=y_column, data=total_recover)

plt.xlabel('Total recover', fontsize=14)
plt.ylabel('Countries', fontsize=12)
plt.title('Top 20 Countries with the Most Recoveries', fontsize=15)

plt.show()

"""# *Number of Recovered Patients is higher in USA AND BRAZIL*"""

total_recover

total_active = df.groupby("Country/Region")["Active"].sum().sort_values(ascending=False).head(20).reset_index()

x_column = 'Active'
y_column = 'Country/Region'

plt.figure(figsize=(10, 6))  # Set the figure size as per your preference

sns.barplot(x=x_column, y=y_column, data=total_active)

plt.xlabel('Total active', fontsize=14)
plt.ylabel('Countries', fontsize=12)
plt.title('Top 20 Countries with the Highest Active Cases', fontsize=15)
plt.show()

total_active

fig = px.sunburst(df, path=['WHO Region', 'Country/Region'], values='Confirmed')

fig.update_layout(width = 700,
                  height = 600,
                  title = 'Total Confirmed',
                  title_x=0.5)

fig.show();

fig = px.sunburst(df, path=['WHO Region', 'Country/Region'], values='Deaths')

fig.update_layout(width = 700,
                  height = 600,
                  title = 'Total Deaths',
                  title_x=0.5)

fig.show();

fig = px.sunburst(df, path=['WHO Region', 'Country/Region'], values='Recovered')

fig.update_layout(width = 700,
                  height = 600,
                  title = 'Total Recovered',
                  title_x=0.5)

fig.show();

fig = px.sunburst(df, path=['WHO Region', 'Country/Region'], values='Active')

fig.update_layout(width = 700,
                  height = 600,
                  title = 'Total Active',
                  title_x=0.5)

fig.show();